package agent

import (
	"context"
	"encoding/json"
	"fmt"
	"regexp"
	"strings"
	"time"

	"studyquest/backend/internal/ai"
	"studyquest/backend/internal/ai/jsonx"
	"studyquest/backend/internal/model"
	"studyquest/backend/internal/repository"
)

// SummaryResult is the structured summary the model returns, parsed from JSON.
// The fields mirror SummarizerSystemPrompt's requested shape. All optional — a
// degenerate lesson may yield empty arrays. This is what gets JSON-encoded into
// ai_summaries.summary_json and served to the client.
type SummaryResult struct {
	Headline  string   `json:"headline"`
	KeyPoints []string `json:"key_points"`
	Concepts  []string `json:"concepts"`
	// Sections 是按知识点分的小节,让总结有结构而非平铺要点。每节有标题(知识点)
	// 和该知识点的要点列表。一节课通常 2-5 节。Phase F 丰富化:从 key_points 升级
	// 到分知识点结构化,前端可渲染成"知识点卡片"。
	Sections []SummarySection `json:"sections"`
	// CommonMistakes 是这节课相关的常见错误/易错点,帮学生避坑。
	CommonMistakes []string `json:"common_mistakes"`
	// Methods 是这节课讲到的具体方法/技巧/公式,单独拎出来便于速查。
	Methods []string `json:"methods"`
	// PreAdventure 是 3 个课前探险问题:开放式思考题 + 一句思考方向提示。
	// 零额外 LLM 调用——和 summary 同一次生成产出,直接落进 summary_json。
	// 前端在播放前展示,引导孩子带着问题进入视频。
	PreAdventure []PreAdventureItem `json:"pre_adventure"`
	Takeaway     string             `json:"takeaway"`
}

// SummarySection 是一个知识点小节:title 是知识点名称,points 是该知识点的
// 要点(每个一句话)。让总结从"一串平铺要点"升级到"按知识点分组",更接近
// 真实的学习笔记结构。
type SummarySection struct {
	Title  string   `json:"title"`
	Points []string `json:"points"`
}

// PreAdventureItem 是一道课前探险问题:prompt 是问题本身(开放式,激发好奇心),
// hint 是一句不剧透答案的思考方向提示。
type PreAdventureItem struct {
	Prompt string `json:"prompt"`
	Hint   string `json:"hint"`
}

// normalize 保证所有切片字段非 nil。模型可能省略某些数组字段(老 prompt 没有
// sections/methods/common_mistakes),json.Unmarshal 留 nil;nil 切片 Marshal 成
// null,前端 .map 会炸。统一初始化成空切片,Marshal 输出 []。
func (s *SummaryResult) normalize() {
	if s.KeyPoints == nil {
		s.KeyPoints = []string{}
	}
	if s.Concepts == nil {
		s.Concepts = []string{}
	}
	if s.Sections == nil {
		s.Sections = []SummarySection{}
	}
	if s.Methods == nil {
		s.Methods = []string{}
	}
	if s.CommonMistakes == nil {
		s.CommonMistakes = []string{}
	}
	if s.PreAdventure == nil {
		s.PreAdventure = []PreAdventureItem{}
	}
}

// SummarizerRequest carries the inputs to one summary generation.
type SummarizerRequest struct {
	EpisodeID   uint
	CourseID    uint
	// SummaryHint 喂 summary agent 的风格/侧重点(如"侧重开局原理""多举例题")。
	// 来自 Course.EffectiveSummaryHint(subject) —— 课程级 AIConfig 空时回退学科级。
	SummaryHint string
	// TermDict 是横切的术语纠错字典(Course.EffectiveTermDict(subject) —— 课程级+学科级合并)。
	// 注入到 user 消息的【术语字典】段,summary 输出时按此纠正字幕同音错字。
	TermDict string
	Subject  string               // e.g. "数学"
	Chunks   []model.ContentChunk // the lesson's text, already segmented
}

// Summarizer generates one structured summary for a lesson by sending the
// lesson's text chunks to the LLM. It does NOT do tool calling or multi-step
// reasoning (that's the quizzer's job in Phase C) — a summary is a single
// extraction pass, so it's a direct Chat call. The decision trace (input
// snapshot, raw response, token usage, timing) is recorded to ai_runs for
// observability — the admin Workflow page can replay exactly what went in and
// came out, which is how you debug a bad summary.
type Summarizer struct {
	llm   ai.LLMProvider
	repo  repository.AIContentRepository
	model string // model name to request (from the chat provider config)
}

// NewSummarizer builds a Summarizer. llm must be a working chat provider;
// modelName is stamped on ai_runs and ai_summaries for traceability (so the
// admin can see "this summary was generated by gpt-5.4-mini").
func NewSummarizer(llm ai.LLMProvider, repo repository.AIContentRepository, modelName string) *Summarizer {
	return &Summarizer{llm: llm, repo: repo, model: modelName}
}

// Summarize generates and persists a summary for one episode.
//
// Flow:
//  1. Assemble the user prompt from the chunks (text + time markers) + course
//     context. Time markers (e.g. "[12:38]") are included so the model can
//     reference "when" something was said — useful context even though the
//     summary itself is thematic, not timestamped.
//  2. One Chat call (temperature 0: summaries should be deterministic, not
//     creative).
//  3. Parse the JSON response. If parsing fails, we still record the raw
//     response as an ai_run (for debugging) and return an error — the job will
//     be marked failed.
//  4. Persist the summary (upsert on episode_id — re-generation replaces).
//  5. Record an ai_run with the full trace.
//
// The jobID is used to link the ai_run back to its triggering job (admin
// observability). 0 for ad-hoc calls.
func (s *Summarizer) Summarize(ctx context.Context, req SummarizerRequest, jobID uint) (*SummaryResult, error) {
	if len(req.Chunks) == 0 {
		return nil, fmt.Errorf("summarizer: no chunks for episode %d", req.EpisodeID)
	}

	userPrompt := buildSummaryUserPrompt(req)
	start := time.Now()

	chatResp, err := s.llm.Chat(ctx, ai.ChatRequest{
		Model:       s.model,
		Temperature: ai.DefaultTemperature,
		// MaxTokens 集中定义在 ai.MaxTokensSummary(含依据:输出结构重 + ep123 截断断裂
		// 事故)。极端长课若仍超限,parseSummaryJSON 走的 jsonx.ParseLLMJSON 截断兜底
		// 会救回前面的 sections 而非全废。
		MaxTokens: ai.MaxTokensSummary,
		Messages: []ai.ChatMessage{
			{Role: ai.RoleSystem, Content: SummarizerSystemPrompt},
			{Role: ai.RoleUser, Content: userPrompt},
		},
	})
	elapsed := time.Since(start)

	// Always record the run, even on error — a failed generation is just as
	// interesting to debug as a successful one. Best-effort: a logging failure
	// must not mask the real result. 把 system+user prompt 一并传入,写进
	// ai_runs.system_prompt_text / user_prompt_text 供 admin "查看回放"。
	runInput := buildRunInput(req)
	if chatResp != nil {
		s.recordRun(jobID, runInput, chatResp, elapsed, SummarizerSystemPrompt, userPrompt)
	} else {
		s.recordRunErr(jobID, runInput, err, elapsed, SummarizerSystemPrompt, userPrompt)
	}
	if err != nil {
		return nil, fmt.Errorf("summarizer: chat call failed: %w", err)
	}

	result, err := parseSummaryJSON(chatResp.Content)
	if err != nil {
		// 解析失败只返回 error,不在这里落 job 状态。理由:runSummaryJob 现在
		// 会重试一次(瞬时截断/relay 抖动),如果这里先把 job 标 failed,service
		// 层重试成功后状态会错乱(failed→done)。job 的最终状态由 service 层
		// 统一决定:重试耗尽才 failJob。recordRunErr 已经把这次失败的 raw 响应
		// 记进 ai_runs(供 admin 回放),诊断信息不丢。
		return nil, fmt.Errorf("summarizer: parse response JSON: %w (raw: %.200s)", err, chatResp.Content)
	}
	// 保证切片非 nil:模型可能省略某些数组字段(老 prompt 生成的 summary 没有
	// sections/methods/common_mistakes),json.Unmarshal 会留 nil。nil 切片
	// json.Marshal 成 null,前端 .map 会炸。这里统一初始化成空切片。
	result.normalize()

	// Persist the summary (upsert).
	summaryJSON, _ := json.Marshal(result)
	if err := s.repo.UpsertSummary(&model.AISummary{
		EpisodeID:   req.EpisodeID,
		CourseID:    req.CourseID,
		SummaryJSON: string(summaryJSON),
		ModelUsed:   s.model,
	}); err != nil {
		return nil, fmt.Errorf("summarizer: persist summary: %w", err)
	}
	return &result, nil
}

// buildSummaryUserPrompt assembles the text sent to the model: course context
// first (sets the domain), then the lesson text with time markers. Time markers
// help the model anchor statements to when they occurred in the lesson — even
// though the summary is thematic, knowing "this was said early" vs "this was the
// conclusion" helps structure the summary.
func buildSummaryUserPrompt(req SummarizerRequest) string {
	var b strings.Builder
	b.WriteString("课程信息:\n")
	if req.Subject != "" {
		b.WriteString("科目:" + req.Subject + "\n")
	}
	// SummaryHint 喂 summary agent 的风格/侧重点(可选)。
	if req.SummaryHint != "" {
		b.WriteString("【总结提示】\n")
		b.WriteString(req.SummaryHint)
		b.WriteString("\n\n")
	}
	// TermDict 注入横切术语字典,让 summary 输出时按此纠正字幕同音错字(可选)。
	if req.TermDict != "" {
		b.WriteString("【术语字典】(输出时按此纠正字幕同音错字)\n")
		b.WriteString(req.TermDict)
		b.WriteString("\n\n")
	}
	b.WriteString("字幕内容(按时间顺序,带时间标记):\n\n")
	for _, ch := range req.Chunks {
		startSec := 0
		if ch.StartTime != nil {
			startSec = *ch.StartTime
		}
		fmt.Fprintf(&b, "[%s] %s\n", mmss(startSec), ch.Text)
	}
	return b.String()
}

// buildRunInput captures a snapshot of what the model SAW for this run, so the
// admin can replay the decision. We include the chunk count and a truncated
// preview (full text would bloat the table; the admin can look at the chunks
// separately if they need the whole input).
func buildRunInput(req SummarizerRequest) string {
	preview := ""
	if len(req.Chunks) > 0 {
		preview = req.Chunks[0].Text
		if len(preview) > 200 {
			preview = preview[:200] + "…"
		}
	}
	in, _ := json.Marshal(map[string]any{
		"episode_id":  req.EpisodeID,
		"chunk_count": len(req.Chunks),
		"subject":     req.Subject,
		"preview":     preview,
	})
	return string(in)
}

// recordRun 写一条成功的 summary ai_run。systemPrompt/userPrompt 是本次发给 LLM 的
// 开场 prompt,写进 ai_runs.system_prompt_text / user_prompt_text 供 admin "查看回放"。
func (s *Summarizer) recordRun(jobID uint, inputJSON string, resp *ai.ChatResponse, elapsed time.Duration, systemPrompt, userPrompt string) {
	s.repo.CreateRun(&model.AIRun{
		JobID:            jobID,
		Capability:       "summary",
		InputJSON:        inputJSON,
		PromptTokens:     resp.Usage.PromptTokens,
		CompletionTokens: resp.Usage.CompletionTokens,
		ModelUsed:        s.model,
		ResponseText:     resp.Content,
		// summary 无自检环节(quiz 才有),复用 SelfCheckResult 字段记生成结果:
		// pass=成功生成,fail=调用失败。和 advice/course_summary/polish 统一,
		// 不再用"skipped"(成功失败都写 skipped,前端无法区分)。
		SelfCheckResult: "pass",
		DurationMs:      int(elapsed.Milliseconds()),
		// 记下这次发给 LLM 的完整 system+user prompt,供 admin "查看回放"还原本次 prompt
		// (原来只存精简 InputJSON 快照,调 prompt 是盲调)。失败时也记——看是哪个 prompt
		// 导致的失败同样有价值。
		SystemPromptText: systemPrompt,
		UserPromptText:   userPrompt,
	})
}

// recordRunErr 写一条失败的 summary ai_run(call 没拿到响应)。systemPrompt/userPrompt
// 同样传入:失败时 prompt 也有诊断价值(可能是某个 prompt 触发了失败)。
func (s *Summarizer) recordRunErr(jobID uint, inputJSON string, err error, elapsed time.Duration, systemPrompt, userPrompt string) {
	s.repo.CreateRun(&model.AIRun{
		JobID:            jobID,
		Capability:       "summary",
		InputJSON:        inputJSON,
		ModelUsed:        s.model,
		ResponseText:     "(call failed) " + err.Error(),
		SelfCheckResult:  "fail",
		DurationMs:       int(elapsed.Milliseconds()),
		SystemPromptText: systemPrompt,
		UserPromptText:   userPrompt,
	})
}

// parseSummaryJSON extracts the structured summary from the model's response.
// 解析统一委托 jsonx.ParseLLMJSON(全项目 LLM JSON 的唯一 chokepoint),兜底链:
//   - extract(围栏剥离/散文夹带剥离):模型被要求输出纯 JSON,但中转站常裹 ```json
//     围栏或夹带散文;extractJSONObject 挖首个平衡对象,并 RECOVER 截断输出
//     (max_tokens 截断时闭合未完结结构,救回前面字段而非整 job 失败)。
//   - 裸引号修复(2026-07-29,与 homework 同源故障):LLM 常在 string value 写未转义
//     裸 ASCII 双引号(如 points 里写"象棋级别"毕业""),第一次 parse 失败时替换成
//     中文「」再 parse。生产 ep2 两次 summary 都因裸引号失败,这套兜底救回。
//
// 后端不支持 response_format 时(探测确认 v2ex/中转站均 400 拒绝),这是主防线;
// 换支持约束解码的后端后,从 provider 层启用 response_format 即可根治,本兜底保留。
func parseSummaryJSON(raw string) (SummaryResult, error) {
	var result SummaryResult
	// 统一走 jsonx.ParseLLMJSON:extract(围栏/截断)→ unmarshal → 失败则裸引号修复
	// → 再 unmarshal。repaired 值此处不外传(summary 调用方不需要),但 repair 兜底
	// 在 jsonx 内部生效,救回 LLM 在 string value 写裸 ASCII 双引号的故障(生产 ep2)。
	if _, err := jsonx.ParseLLMJSON(raw, &result); err != nil {
		return result, fmt.Errorf("invalid JSON: %w", err)
	}
	result.normalizeMarkdownInFields()
	return result, nil
}

// normalizeMarkdownInFields 修两类模型常见的脏数据(在生产 DB 里已确认出现):
//
//  1. **字面量 `\n` 没解成真实换行**:LLM 在 JSON 字符串值里输出表格时,有时
//     把 `\n` 当 2 字符字面量(backslash+n)而非换行转义。json.Unmarshal 不会
//     再解一次,字面量 `\n` 留在字符串里 → GFM 表格 `| a |\n|---|` 在客户端
//     是一行,markdown 不识别为表格 → 渲染成纯文字。
//
//  2. **裸 `<svg>...</svg>` 没加围栏**:prompt 要求 SVG 放 ``` ```svg ``` 围栏,
//     但模型有时直接吐裸 SVG → markdown 把它当内联 HTML 转义掉 → 渲染成文本。
//     这里自动补围栏,让客户端 _SvgCodeInterceptor 能拦截。
//
// 同时作用在所有承载 markdown 的字段:Headline / KeyPoints / Sections[*].Points /
// Methods / CommonMistakes / Takeaway。
func (r *SummaryResult) normalizeMarkdownInFields() {
	r.Headline = normalizeOneMarkdownField(r.Headline)
	r.Takeaway = normalizeOneMarkdownField(r.Takeaway)
	for i := range r.KeyPoints {
		r.KeyPoints[i] = normalizeOneMarkdownField(r.KeyPoints[i])
	}
	for i := range r.Methods {
		r.Methods[i] = normalizeOneMarkdownField(r.Methods[i])
	}
	for i := range r.CommonMistakes {
		r.CommonMistakes[i] = normalizeOneMarkdownField(r.CommonMistakes[i])
	}
	for i := range r.Sections {
		r.Sections[i].Title = normalizeOneMarkdownField(r.Sections[i].Title)
		for j := range r.Sections[i].Points {
			r.Sections[i].Points[j] = normalizeOneMarkdownField(r.Sections[i].Points[j])
		}
	}
}

// normalizeOneMarkdownField 对单个字段做 normalize:字面量 \n→换行,裸 svg→加围栏。
// 不碰已经在 ``` 围栏里的内容(避免破坏已正确的 SVG 块)。
func normalizeOneMarkdownField(s string) string {
	if s == "" {
		return s
	}
	// 按 ``` 分段:奇数段(代码块内容)原样保留,偶数段(普通 markdown)做替换。
	parts := strings.Split(s, "```")
	var b strings.Builder
	for i, p := range parts {
		if i%2 == 1 {
			b.WriteString("```")
			b.WriteString(p)
			b.WriteString("```")
			continue
		}
		// 字面量 \n / \r / \t → 真实字符。
		p = strings.ReplaceAll(p, "\\n", "\n")
		p = strings.ReplaceAll(p, "\\r", "")
		p = strings.ReplaceAll(p, "\\t", "\t")
		// 裸 <svg ...>...</svg> 自动加围栏。
		p = wrapBareSvg(p)
		b.WriteString(p)
	}
	return b.String()
}

// wrapBareSvg 把段内所有裸 <svg ... </svg>(没有 ```svg 围栏包裹的)替换成
// 围栏代码块。调用方已经把代码块段隔离掉了,所以这里只需要匹配裸 SVG。
var bareSvgRe = regexp.MustCompile(`(?s)<svg\b.*?</svg>`)

func wrapBareSvg(s string) string {
	if !strings.Contains(strings.ToLower(s), "<svg") {
		return s
	}
	return bareSvgRe.ReplaceAllStringFunc(s, func(m string) string {
		return "\n```svg\n" + m + "\n```\n"
	})
}

// mmss is duplicated from the segmenter package to keep the agent package
// self-contained (it has no dependency back to the root ai package's helper).
// Formats seconds as M:SS or H:MM:SS for prompt time markers.
func mmss(seconds int) string {
	h := seconds / 3600
	m := (seconds % 3600) / 60
	sec := seconds % 60
	if h > 0 {
		return fmt.Sprintf("%d:%02d:%02d", h, m, sec)
	}
	return fmt.Sprintf("%02d:%02d", m, sec)
}
