package service

// ──────────────────────────────────────────────────────────────────────────────
// Single source of truth for system-seeded entity keys.
//
// These lists are referenced by BOTH the SeedDefault* methods (which insert
// the rows) AND cmd/server/main.go's markSystemDefaults (which backfills
// is_system=true on pre-existing installs). Keeping them in one place removes
// the old drift risk where main.go hand-redeclared the same keys with a
// comment saying "must stay in sync" — they now literally can't diverge.
// ──────────────────────────────────────────────────────────────────────────────

// SystemSubjectKeys are the keys of the seeded-default subjects. These rows
// carry IsSystem=true and are delete-protected (see ErrSystemProtected).
//
// 2026-07-20:entertainment 单行已删除,换成 4 个具体娱乐子类(animation/movie/
// documentary/variety)。注意:这份列表目前是死代码(grep 全仓无引用方,原本是给
// 不存在的 markSystemDefaults 函数用的),保留仅供参考,真正的 seed 真源在
// subject_service.go 的 defaults slice。
var SystemSubjectKeys = []string{
	"chinese", "math", "english", "physics",
	"chemistry", "biology", "history", "geography", "politics",
	"extra",
	// 娱乐子类(Category=entertainment,不 seed badge):
	"animation", "movie", "documentary", "variety",
}

// SystemTagKeys are the keys of the seeded-default tags.
var SystemTagKeys = []string{
	"required", "thinking", "extension", "explore", "extracurricular", "logic", "horizon",
}

// SystemBadgeCodes are the codes of the seeded-default core badges. Subject
// badges (subject_<key>) are auto-generated by SubjectService and also marked
// IsSystem at creation; they're not listed here because they're dynamic.
var SystemBadgeCodes = []string{
	"first_blood", "streak", "episode_master", "time_master", "points_hero", "explorer",
	"course_master", "weekly_dedication",
}
